### ISSUE TITLE
Move batch-processor to scijava org

### ISSUE THREAD

**Issue by imagejan** [scijava/batch-processor#8]
This repository should live in the `scijava` org, so that other SciJava projects can use it more easily.

@ctrueden any objections against me moving this?

**Comment by ctrueden** [comment]
Great! Please do it! But it depends on `net.imagej:imagej`, so should move to the imagej org, no?

**Comment by ctrueden** [comment]
The only question is: is it image-specific? If so, move it to imagej instead.

**Comment by imagejan** [comment]
@ctrueden the `net.imagej:imagej` dependency is just because I'm using a `net.imagej.table.Table` here:

https://github.com/fmi-faim/batch-processor/blob/6aa2740088c085417f90572baa944a6a0ab11702/src/main/java/org/scijava/batch/ModuleBatchProcessor.java#L11-L13

Are there any reasons why `Table` lives in `imagej` and not `scijava`?

**Comment by ctrueden** [comment]
> Are there any reasons why `Table` lives in `imagej` and not `scijava`?

Not any good ones. 😛 

As part of SciJava 3, we can create a new `scijava-table` component and move the code there. (SciJava 3 will see a lot of development effort from me soon.) In the meantime, I guess it's fine to move this to the scijava org as is, with the idea that we will be ironing out that dependency wrinkle.

**Comment by imagejan** [comment]
I just noticed that I don't have the permission to create repositories in the `scijava` org.
@ctrueden: would you grant me permission for this move, please? :-)

**Comment by imagejan** [comment]
Done.
